#!/usr/bin/env python3
"""Lightweight onboarding, task map, and demo helper for scrumball-skills."""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
from collections import defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV_FILE = ROOT / ".env"
TASK_MAP_PATH = ROOT / "docs" / "task-map.json"
PLATFORMS = {"instagram", "tiktok", "youtube"}
DEFAULT_TASK_MAP_IGNORE_OPERATIONS = {"ping"}


def load_env_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            continue
        if key not in os.environ:
            os.environ[key] = value.strip().strip('"').strip("'")
    return True


def resolve_and_load_env(env_file_arg: str | None) -> Path | None:
    candidates = []
    if env_file_arg:
        candidates.append(Path(env_file_arg).expanduser())
    elif os.getenv("SCRUMBALL_ENV_FILE"):
        candidates.append(Path(os.getenv("SCRUMBALL_ENV_FILE", "")).expanduser())
    else:
        candidates.append(DEFAULT_ENV_FILE)

    for candidate in candidates:
        if load_env_file(candidate):
            return candidate
    return None


def auth_header_value(api_key: str) -> str:
    prefix = os.getenv("SCRUMBALL_AUTH_PREFIX", "").strip()
    return f"{prefix} {api_key}" if prefix else api_key


def mask_secret(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 8:
        return "*" * len(value)
    return f"{value[:4]}...{value[-2:]}"


def parse_timeout(raw: str) -> int:
    try:
        timeout = int(raw)
    except ValueError as exc:
        raise ValueError("Timeout must be an integer number of seconds") from exc
    if timeout <= 0:
        raise ValueError("Timeout must be greater than zero")
    return timeout


def collect_env_values(args: argparse.Namespace) -> dict[str, str]:
    current_base_url = args.base_url or os.getenv("SCRUMBALL_BASE_URL", "").strip()
    current_api_key = args.api_key or os.getenv("SCRUMBALL_API_KEY", "").strip()
    current_prefix = args.auth_prefix
    if current_prefix is None:
        current_prefix = os.getenv("SCRUMBALL_AUTH_PREFIX", "").strip()
    current_timeout = str(args.timeout) if args.timeout is not None else os.getenv("SCRUMBALL_TIMEOUT_SECONDS", "30")

    if args.non_interactive:
        if not current_base_url:
            raise ValueError("Missing --base-url for non-interactive init")
        if not current_api_key:
            raise ValueError("Missing --api-key for non-interactive init")
        timeout = parse_timeout(current_timeout)
        return {
            "SCRUMBALL_BASE_URL": current_base_url,
            "SCRUMBALL_API_KEY": current_api_key,
            "SCRUMBALL_AUTH_PREFIX": current_prefix,
            "SCRUMBALL_TIMEOUT_SECONDS": str(timeout),
        }

    base_url = input(f"SCRUMBALL_BASE_URL [{current_base_url or 'https://your-gateway.example.com'}]: ").strip() or current_base_url
    api_key = input(f"SCRUMBALL_API_KEY [{mask_secret(current_api_key) or 'paste key'}]: ").strip() or current_api_key
    auth_prefix = input(f"SCRUMBALL_AUTH_PREFIX [{current_prefix or 'optional, e.g. Bearer'}]: ").strip() or current_prefix
    timeout_raw = input(f"SCRUMBALL_TIMEOUT_SECONDS [{current_timeout}]: ").strip() or current_timeout

    if not base_url:
        raise ValueError("SCRUMBALL_BASE_URL is required")
    if not api_key:
        raise ValueError("SCRUMBALL_API_KEY is required")

    timeout = parse_timeout(timeout_raw)
    return {
        "SCRUMBALL_BASE_URL": base_url,
        "SCRUMBALL_API_KEY": api_key,
        "SCRUMBALL_AUTH_PREFIX": auth_prefix,
        "SCRUMBALL_TIMEOUT_SECONDS": str(timeout),
    }


def write_env_file(path: Path, values: dict[str, str], overwrite: bool) -> None:
    existing: dict[str, str] = {}
    if path.exists():
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            existing[key.strip()] = value.strip().strip('"').strip("'")

    merged = {} if overwrite else dict(existing)
    merged.update(values)
    lines = [
        "# Generated by scripts/scrumball_cli.py init",
        f'SCRUMBALL_BASE_URL="{merged["SCRUMBALL_BASE_URL"]}"',
        f'SCRUMBALL_API_KEY="{merged["SCRUMBALL_API_KEY"]}"',
    ]
    if merged.get("SCRUMBALL_AUTH_PREFIX"):
        lines.append(f'SCRUMBALL_AUTH_PREFIX="{merged["SCRUMBALL_AUTH_PREFIX"]}"')
    lines.append(f'SCRUMBALL_TIMEOUT_SECONDS="{merged.get("SCRUMBALL_TIMEOUT_SECONDS", "30")}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ping(base_url: str, api_key: str, timeout: int) -> dict[str, Any]:
    url = base_url.rstrip("/") + "/api/ping"
    req = urllib.request.Request(
        url=url,
        method="GET",
        headers={
            "authorization": auth_header_value(api_key),
            "accept": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read().decode("utf-8")
            try:
                payload = json.loads(raw) if raw else None
            except json.JSONDecodeError:
                payload = raw
            return {"ok": True, "status": resp.getcode(), "url": url, "data": payload}
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace") if exc.fp else ""
        try:
            payload = json.loads(raw) if raw else None
        except json.JSONDecodeError:
            payload = raw
        return {"ok": False, "status": exc.code, "url": url, "error": payload}
    except urllib.error.URLError as exc:
        return {"ok": False, "status": None, "url": url, "error": f"Network error: {exc}"}


def load_task_map() -> list[dict[str, Any]]:
    return json.loads(TASK_MAP_PATH.read_text(encoding="utf-8"))


def load_operations_index() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for operations_path in sorted((ROOT / "skills").glob("*/references/operations.json")):
        skill = operations_path.parent.parent.name
        operations = json.loads(operations_path.read_text(encoding="utf-8"))
        for operation_id, metadata in operations.items():
            platform, family = classify_operation(metadata.get("path", ""))
            records.append(
                {
                    "skill": skill,
                    "operation_id": operation_id,
                    "path": metadata.get("path", ""),
                    "platform": platform,
                    "family": family,
                }
            )
    return records


def classify_operation(raw_path: str) -> tuple[str, str]:
    segments = [segment for segment in raw_path.strip("/").split("/") if segment]
    if segments[:2] == ["api", "v1"]:
        segments = segments[2:]
    elif segments[:1] == ["api"]:
        segments = segments[1:]

    if not segments:
        return "cross-platform", "root"

    head = segments[0]
    if head == "search":
        if len(segments) >= 3 and segments[1] in PLATFORMS:
            return segments[1], "search/" + "/".join(segments[2:])
        return "cross-platform", "search/" + "/".join(segments[1:])

    if head == "audience":
        if len(segments) >= 3 and segments[1] in PLATFORMS:
            return segments[1], "audience/" + "/".join(segments[2:])
        return "cross-platform", "audience/" + "/".join(segments[1:])

    if head == "monitor":
        return "cross-platform", "monitor/" + "/".join(segments[1:])

    if head in PLATFORMS:
        platform = head
        remainder = segments[1:]
        if remainder[:1] == ["realtime"]:
            suffix = "/".join(remainder[1:]) or "root"
            return platform, f"realtime/{suffix}"
        return platform, "/".join(remainder) or "root"

    return "cross-platform", "/".join(segments)


def build_task_map_coverage_report(ignore_operations: set[str] | None = None) -> dict[str, Any]:
    ignore_operations = set(ignore_operations or DEFAULT_TASK_MAP_IGNORE_OPERATIONS)
    tasks = load_task_map()
    operations = load_operations_index()
    operation_lookup = {record["operation_id"]: record for record in operations}

    duplicate_task_ids: list[str] = []
    seen_task_ids: set[str] = set()
    for task in tasks:
        task_id = task["id"]
        if task_id in seen_task_ids:
            duplicate_task_ids.append(task_id)
        seen_task_ids.add(task_id)

    unknown_task_operations: list[dict[str, str]] = []
    platform_mismatches: list[dict[str, str]] = []
    skill_mismatches: list[dict[str, str]] = []
    tasks_by_operation: dict[str, list[str]] = defaultdict(list)

    for task in tasks:
        operation_id = task["operation"]
        tasks_by_operation[operation_id].append(task["id"])
        operation = operation_lookup.get(operation_id)
        if operation is None:
            unknown_task_operations.append({"task_id": task["id"], "operation_id": operation_id})
            continue
        if task["skill"] != operation["skill"]:
            skill_mismatches.append(
                {
                    "task_id": task["id"],
                    "operation_id": operation_id,
                    "task_skill": task["skill"],
                    "operation_skill": operation["skill"],
                }
            )
        if task["platform"] != operation["platform"]:
            platform_mismatches.append(
                {
                    "task_id": task["id"],
                    "operation_id": operation_id,
                    "task_platform": task["platform"],
                    "operation_platform": operation["platform"],
                }
            )

    candidate_operations = [
        operation
        for operation in operations
        if operation["operation_id"] not in ignore_operations
    ]
    unmapped_operations = [
        {
            "skill": operation["skill"],
            "platform": operation["platform"],
            "family": operation["family"],
            "operation_id": operation["operation_id"],
        }
        for operation in candidate_operations
        if operation["operation_id"] not in tasks_by_operation
    ]

    capability_groups: dict[tuple[str, str], dict[str, Any]] = {}
    for operation in candidate_operations:
        key = (operation["skill"], operation["family"])
        group = capability_groups.setdefault(
            key,
            {
                "skill": operation["skill"],
                "family": operation["family"],
                "platforms": set(),
                "operations": [],
                "mapped_operations": [],
                "unmapped_operations": [],
                "task_ids": set(),
            },
        )
        group["platforms"].add(operation["platform"])
        group["operations"].append(operation["operation_id"])
        task_ids = tasks_by_operation.get(operation["operation_id"], [])
        if task_ids:
            group["mapped_operations"].append(operation["operation_id"])
            group["task_ids"].update(task_ids)
        else:
            group["unmapped_operations"].append(operation["operation_id"])

    fully_unmapped_groups = []
    partial_groups = []
    for group in capability_groups.values():
        serializable_group = {
            "skill": group["skill"],
            "family": group["family"],
            "platforms": sorted(group["platforms"]),
            "operations": sorted(group["operations"]),
            "mapped_operations": sorted(group["mapped_operations"]),
            "unmapped_operations": sorted(group["unmapped_operations"]),
            "task_ids": sorted(group["task_ids"]),
        }
        if not group["mapped_operations"]:
            fully_unmapped_groups.append(serializable_group)
        elif group["unmapped_operations"]:
            partial_groups.append(serializable_group)

    return {
        "summary": {
            "task_count": len(tasks),
            "operation_count": len(operations),
            "operation_count_checked": len(candidate_operations),
            "ignored_operation_count": len(operations) - len(candidate_operations),
            "capability_group_count": len(capability_groups),
        },
        "ignored_operations": sorted(ignore_operations),
        "errors": {
            "duplicate_task_ids": sorted(set(duplicate_task_ids)),
            "unknown_task_operations": unknown_task_operations,
        },
        "warnings": {
            "skill_mismatches": skill_mismatches,
            "platform_mismatches": platform_mismatches,
            "unmapped_operations": sorted(unmapped_operations, key=lambda item: item["operation_id"]),
            "fully_unmapped_groups": sorted(fully_unmapped_groups, key=lambda item: (item["skill"], item["family"])),
            "partial_groups": sorted(partial_groups, key=lambda item: (item["skill"], item["family"])),
        },
    }


def print_task_map_coverage_report(report: dict[str, Any]) -> None:
    summary = report["summary"]
    print(
        "Checked "
        f"{summary['task_count']} tasks against {summary['operation_count_checked']} operations "
        f"across {summary['capability_group_count']} capability groups."
    )
    if summary["ignored_operation_count"]:
        print(f"Ignored operations: {', '.join(report['ignored_operations'])}")

    duplicate_task_ids = report["errors"]["duplicate_task_ids"]
    unknown_task_operations = report["errors"]["unknown_task_operations"]
    skill_mismatches = report["warnings"]["skill_mismatches"]
    platform_mismatches = report["warnings"]["platform_mismatches"]
    unmapped_operations = report["warnings"]["unmapped_operations"]
    fully_unmapped_groups = report["warnings"]["fully_unmapped_groups"]
    partial_groups = report["warnings"]["partial_groups"]

    if not any(
        [
            duplicate_task_ids,
            unknown_task_operations,
            skill_mismatches,
            platform_mismatches,
            unmapped_operations,
            fully_unmapped_groups,
            partial_groups,
        ]
    ):
        print("OK: semantic task-map coverage is in sync with the current capability surface.")
        return

    if duplicate_task_ids:
        print("ERROR duplicate task IDs:")
        for task_id in duplicate_task_ids:
            print(f"  - {task_id}")

    if unknown_task_operations:
        print("ERROR tasks pointing to unknown operations:")
        for item in unknown_task_operations:
            print(f"  - {item['task_id']} -> {item['operation_id']}")

    if skill_mismatches:
        print("WARN task/operation skill mismatches:")
        for item in skill_mismatches:
            print(
                "  - "
                f"{item['task_id']} -> {item['operation_id']} "
                f"(task={item['task_skill']}, operation={item['operation_skill']})"
            )

    if platform_mismatches:
        print("WARN task/operation platform mismatches:")
        for item in platform_mismatches:
            print(
                "  - "
                f"{item['task_id']} -> {item['operation_id']} "
                f"(task={item['task_platform']}, operation={item['operation_platform']})"
            )

    if fully_unmapped_groups:
        print("WARN fully unmapped capability groups:")
        for item in fully_unmapped_groups:
            platforms = ", ".join(item["platforms"])
            operations = ", ".join(item["operations"])
            print(f"  - {item['skill']} :: {item['family']} [{platforms}] -> {operations}")

    if partial_groups:
        print("WARN partially mapped capability groups:")
        for item in partial_groups:
            platforms = ", ".join(item["platforms"])
            mapped = ", ".join(item["mapped_operations"])
            missing = ", ".join(item["unmapped_operations"])
            print(
                f"  - {item['skill']} :: {item['family']} [{platforms}] "
                f"mapped={mapped} missing={missing}"
            )

    if unmapped_operations:
        print("WARN unmapped operations:")
        for item in unmapped_operations:
            print(
                f"  - {item['operation_id']} "
                f"({item['skill']} / {item['platform']} / {item['family']})"
            )


def cmd_check_task_map(args: argparse.Namespace) -> int:
    ignore_operations = set(DEFAULT_TASK_MAP_IGNORE_OPERATIONS)
    ignore_operations.update(args.ignore_operation or [])
    report = build_task_map_coverage_report(ignore_operations=ignore_operations)

    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print_task_map_coverage_report(report)

    has_errors = any(report["errors"].values())
    has_warnings = any(report["warnings"].values())
    if has_errors or (args.strict and has_warnings):
        return 1
    return 0


def parse_params(pairs: list[str]) -> dict[str, Any]:
    data: dict[str, Any] = {}
    for pair in pairs:
        if "=" not in pair:
            raise ValueError(f"Invalid --param value: {pair}. Use key=value")
        key, raw = pair.split("=", 1)
        key = key.strip()
        if not key:
            raise ValueError(f"Invalid --param value: {pair}. Key is empty")
        value = raw.strip()
        if value.lower() in {"true", "false"}:
            data[key] = value.lower() == "true"
            continue
        if value.isdigit():
            data[key] = int(value)
            continue
        data[key] = value
    return data


def find_task(task_id: str) -> dict[str, Any]:
    for task in load_task_map():
        if task["id"] == task_id:
            return task
    raise ValueError(f"Unknown task: {task_id}")


def run_task(task: dict[str, Any], env_file: Path, params: dict[str, Any], dry_run: bool, use_example: bool) -> int:
    payload = dict(task.get("example", {})) if use_example else {}
    payload.update(params)
    required = task.get("required", [])
    required_any = task.get("required_any", [])

    missing = [key for key in required if payload.get(key) in (None, "")]
    if missing:
        print(f"ERROR: Missing required fields: {', '.join(missing)}")
        print(f"Follow-up: {task['missing_follow_up']}")
        if task.get("example"):
            print("Optional shortcut: re-run with --use-example to seed the documented sample payload.")
        return 1
    if required_any and not any(payload.get(key) not in (None, "") for key in required_any):
        print(f"ERROR: Missing one of: {', '.join(required_any)}")
        print(f"Follow-up: {task['missing_follow_up']}")
        if task.get("example"):
            print("Optional shortcut: re-run with --use-example to seed the documented sample payload.")
        return 1

    skill_script = ROOT / "skills" / task["skill"] / "scripts" / "execute_operation.py"
    mode = task.get("parameter_mode", "query")
    command = [
        sys.executable,
        str(skill_script),
        "--env-file",
        str(env_file),
        "call",
        "--operation",
        task.get("demo_operation") or task["operation"],
        f"--{mode}",
        json.dumps(payload, ensure_ascii=False),
    ]

    print(f"Task: {task['id']} -> {task.get('demo_operation') or task['operation']}")
    print(f"Skill: {task['skill']}")
    print(f"Params: {json.dumps(payload, ensure_ascii=False)}")
    if dry_run:
        print("Dry run only. Underlying command:")
        print(" ".join(command))
        return 0

    completed = subprocess.run(command, cwd=ROOT)
    return completed.returncode


def cmd_init(args: argparse.Namespace) -> int:
    resolve_and_load_env(args.env_file)
    env_file = Path(args.env_file).expanduser() if args.env_file else DEFAULT_ENV_FILE
    values = collect_env_values(args)
    write_env_file(env_file, values, overwrite=args.overwrite)
    print(f"Wrote {env_file}")
    print(f"Base URL: {values['SCRUMBALL_BASE_URL']}")
    print(f"API key: {mask_secret(values['SCRUMBALL_API_KEY'])}")
    if args.skip_ping:
        print("Skipped ping check")
        return 0

    result = ping(values["SCRUMBALL_BASE_URL"], values["SCRUMBALL_API_KEY"], int(values["SCRUMBALL_TIMEOUT_SECONDS"]))
    print(json.dumps({"ping": result}, ensure_ascii=False, indent=2))
    return 0 if result.get("ok") else 1


def cmd_doctor(args: argparse.Namespace) -> int:
    loaded = resolve_and_load_env(args.env_file)
    env_file = Path(args.env_file).expanduser() if args.env_file else (loaded or DEFAULT_ENV_FILE)
    base_url = os.getenv("SCRUMBALL_BASE_URL", "").strip()
    api_key = os.getenv("SCRUMBALL_API_KEY", "").strip()
    timeout = int(os.getenv("SCRUMBALL_TIMEOUT_SECONDS", "30"))

    result: dict[str, Any] = {
        "ok": bool(base_url and api_key),
        "env_file": str(env_file),
        "loaded_env_file": str(loaded) if loaded else None,
        "base_url_configured": bool(base_url),
        "api_key_configured": bool(api_key),
        "base_url": base_url or None,
        "auth_prefix": os.getenv("SCRUMBALL_AUTH_PREFIX", "").strip() or None,
        "timeout_seconds": timeout,
        "next_step": None,
    }
    if not base_url or not api_key:
        result["next_step"] = f"Run: {sys.executable} scripts/scrumball_cli.py init"
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 1

    if args.skip_ping:
        result["next_step"] = f"Run: {sys.executable} scripts/scrumball_cli.py demo"
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0

    result["ping"] = ping(base_url, api_key, timeout)
    result["ok"] = bool(result["ok"] and result["ping"].get("ok"))
    result["next_step"] = f"Run: {sys.executable} scripts/scrumball_cli.py demo" if result["ok"] else "Check base URL, API key, auth prefix, and network access"
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result["ok"] else 1


def cmd_tasks(args: argparse.Namespace) -> int:
    tasks = load_task_map()
    if args.skill:
        tasks = [task for task in tasks if task["skill"] == args.skill]
    if args.search:
        term = args.search.lower()
        tasks = [
            task
            for task in tasks
            if term in task["id"].lower()
            or term in task["title"].lower()
            or term in task["summary"].lower()
        ]
    if args.json:
        print(json.dumps(tasks, ensure_ascii=False, indent=2))
        return 0

    for task in tasks:
        required = task.get("required") or task.get("required_any") or []
        print(f"{task['id']}\t{task['skill']}\t{task['operation']}\tneeds: {', '.join(required) or 'none'}")
        print(f"  {task['title']}: {task['summary']}")
        print(f"  Ask if missing: {task['missing_follow_up']}")
    print(f"TOTAL\t{len(tasks)}")
    return 0


def cmd_demo(args: argparse.Namespace) -> int:
    resolve_and_load_env(args.env_file)
    env_file = Path(args.env_file).expanduser() if args.env_file else DEFAULT_ENV_FILE
    if not args.task:
        print("Quick demo flow:")
        print(f"1. {sys.executable} scripts/scrumball_cli.py doctor")
        print(f"2. {sys.executable} scripts/scrumball_cli.py tasks")
        print(f"3. {sys.executable} scripts/scrumball_cli.py demo --task lead.find-tiktok-creators --param query=nike")
        print(f"4. {sys.executable} scripts/scrumball_cli.py demo --task monitor.list-active-video-tasks")
        print(f"5. {sys.executable} scripts/scrumball_cli.py demo --task lead.find-tiktok-creators --use-example --dry-run")
        return 0

    params = parse_params(args.param or [])
    task = find_task(args.task)
    return run_task(task, env_file, params, dry_run=args.dry_run, use_example=args.use_example)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Onboarding and quick-task helper for scrumball-skills")
    parser.add_argument("--env-file", help="Optional env file path; defaults to ./.env")

    sub = parser.add_subparsers(dest="cmd", required=True)

    p_init = sub.add_parser("init", help="Create or update .env and optionally verify with ping")
    p_init.add_argument("--base-url")
    p_init.add_argument("--api-key")
    p_init.add_argument("--auth-prefix")
    p_init.add_argument("--timeout", type=int)
    p_init.add_argument("--overwrite", action="store_true", help="Replace existing env values instead of merging")
    p_init.add_argument("--skip-ping", action="store_true")
    p_init.add_argument("--non-interactive", action="store_true")
    p_init.set_defaults(func=cmd_init)

    p_doctor = sub.add_parser("doctor", help="Check env and ping the gateway")
    p_doctor.add_argument("--skip-ping", action="store_true")
    p_doctor.set_defaults(func=cmd_doctor)

    p_tasks = sub.add_parser("tasks", help="List high-level tasks mapped to operations")
    p_tasks.add_argument("--skill")
    p_tasks.add_argument("--search")
    p_tasks.add_argument("--json", action="store_true")
    p_tasks.set_defaults(func=cmd_tasks)

    p_demo = sub.add_parser("demo", help="Run a starter task without memorizing operationIds")
    p_demo.add_argument("--task")
    p_demo.add_argument("--param", action="append", help="Task parameter in key=value form")
    p_demo.add_argument("--use-example", action="store_true", help="Seed the task's documented example payload before applying --param overrides")
    p_demo.add_argument("--dry-run", action="store_true")
    p_demo.set_defaults(func=cmd_demo)

    p_check = sub.add_parser("check-task-map", help="Warn when operations or capability groups drift out of the semantic task map")
    p_check.add_argument("--strict", action="store_true", help="Exit non-zero when warnings are found")
    p_check.add_argument("--json", action="store_true", help="Print the report as JSON")
    p_check.add_argument(
        "--ignore-operation",
        action="append",
        help="OperationId to ignore during coverage checks; can be passed multiple times",
    )
    p_check.set_defaults(func=cmd_check_task_map)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        return args.func(args)
    except ValueError as exc:
        print(f"ERROR: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
